### ISSUE TITLE
How are these blog images drawn?

### ISSUE THREAD

**Issue by JimmyLv** [Hiswe/hiswe.github.io#8]
Sorry for the inappropriate usage of GitHub issue.

I couldn't found the comments inside your blog website, so that I just open this issue for the question, how these beautiful images drawn in your articles?

e.g. https://github.com/Hiswe/hiswe.github.io/blob/master/2018/12-vue-with-nuxt/structure.svg

**Comment by Hiswe** [comment]
@JimmyLv I just draw them myself with Affinity Designer :)
Thanks ^^
